# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('route_short_name', models.TextField()),
                ('route_long_name', models.TextField()),
                ('route_type', models.TextField()),
                ('route_color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stop_code', models.IntegerField()),
                ('stop_name', models.TextField()),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('zone_id', models.IntegerField()),
                ('stop_url', models.TextField()),
                ('location_type', models.IntegerField()),
                ('parent_station', models.CharField(max_length=20)),
                ('platform_code', models.CharField(max_length=20)),
                ('wheelchair_boarding', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop_sequence', models.IntegerField()),
                ('pickup_type', models.IntegerField()),
                ('drop_off_type', models.IntegerField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caltraindb.Stop')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('trip_headsign', models.TextField()),
                ('trip_short_name', models.TextField()),
                ('service_id', models.TextField()),
                ('direction_id', models.IntegerField()),
                ('wheelchair_accessible', models.BooleanField()),
                ('bikes_allowed', models.BooleanField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caltraindb.Route')),
            ],
        ),
        migrations.AddField(
            model_name='stoptime',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caltraindb.Trip'),
        ),
    ]
