# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caltraindb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='stop_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='arrival_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='departure_time',
            field=models.CharField(max_length=20),
        ),
    ]
