# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caltraindb', '0002_auto_20160520_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='zone_id',
            field=models.CharField(max_length=20),
        ),
    ]
